### ISSUE TITLE
Deploying grounds.io

### ISSUE THREAD

**Issue by bparanj** [grounds/grounds.io#108]
I need help to deploy grounds.io to my server.

**Comment by folieadrien** [comment]
Wich operating system are you running on your server?
Do you already have docker installed on it?

**Comment by bparanj** [comment]
I have not selected a host yet. I have a few sites deployed on Linode and GAE. Linode runs on Ubunutu. I have not installed docker. Do you think Linode 1GB plan will work ?

**Comment by folieadrien** [comment]
I am no expert with linode, but it seems to be pretty close to Digitalocean (which I used to deploy grounds.io). Ubuntu is a perfect fit to install docker.

I am using this shell [script](https://github.com/grounds/droplets/blob/master/scripts/provision.sh) to install every dependencies required to run grounds.io on ubuntu.

Then just follow this [documentation](http://www.virtuallyghetto.com/2014/07/quick-tip-how-to-enable-docker-remote-api.html) to expose Docker API to the outside world.

Then you should be ready to launch grounds with our [documentation](https://github.com/grounds/grounds.io/blob/master/README.md).

Don't hesitate if your any facing any issue, the documentation is quite new, it will be really helpful for us.

**Comment by bparanj** [comment]
Which one should I select, Ubuntu 14.10 or 14.04 LTS? Should I run that script as root?

**Comment by folieadrien** [comment]
14.04 LTS. Yes, it won't work otherwise I think.

**Comment by bparanj** [comment]
I pulled one docker image.

docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
ubuntu              latest              5ba9dab47459        5 days ago          192.7 MB

I got the following reponse after exposing the Docker API.

curl -X GET http://45.56.73.253:4243/images/json
[{"Created":1422470238,"Id":"5ba9dab47459d81c0037ca3836a368a4f8ce5050505ce89720e1fb8839ea048a","ParentId":"51a9c7c1f8bb2fa19bcd09789a34e63f35abb80044bc10196e304f6634cc582c","RepoTags":["ubuntu:latest"],"Size":0,"VirtualSize":192683476}
]

Does this look good for the next step?

**Comment by bparanj** [comment]
I get the following error when I run 'make pull'

root@li923-253:~# make pull
make: *** No rule to make target `pull'.  Stop.

**Comment by folieadrien** [comment]
You configuration for the docker API seems good.

I guess you need to be in grounds.io directory to use make with the appropriate Makefile.

**Comment by bparanj** [comment]
When I run, 'make run' I am getting the following error:

Rails Error: Unable to access log file. Please ensure that /grounds/log/development.log exists and is writable (ie, make it writable for user and group: chmod 0664 /grounds/log/development.log). The log level has been raised to WARN and the output directed to STDERR until the problem is fixed.
web_1   |   REDIS_URL=redis://172.17.0.9:6379   RUNNER_URL=http://:8080   bundle exec rails server -b 0.0.0.0 -p 3000
web_1   | => Booting Puma
web_1   | => Rails 4.2.0 application starting in development on http://0.0.0.0:3000
web_1   | => Run `rails server -h` for more startup options
web_1   | => Ctrl-C to shutdown server
web_1   | Exiting
web_1   | /usr/local/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /grounds/tmp (Errno::EACCES)

**Comment by folieadrien** [comment]
Can you try `chmod -R 0664 grounds.io` after cloning the project ?
If it doesn't work, maybe try again with 777 instead of 0664. 

Also, don't forget to setup in your environment "DOCKER_URL" with your docker api http url.

**Comment by bparanj** [comment]
I had to chmod 777 to get it working. Now when I access the site: http://45.56.73.253:3000, I get:

Connection with remote server failed. Trying to reconnect...

in the console section.

**Comment by folieadrien** [comment]
`DOCKER_URL=http://45.56.73.253:4243 make run`

Or `export DOCKER_URL=http://45.56.73.253:4243` then `make run` should work.

**Comment by bparanj** [comment]
It's working now. Should I use:

nohup RAILS_ENV=production make run

to run in the background?

**Comment by folieadrien** [comment]
Great! If you want to benefit from assets precompilation and minification, yes you should.

**Comment by bparanj** [comment]
I am accessing it by specifying the port like this: http://45.56.73.253:3000
I want to map it to my domain without having to specify the port number. Any suggestions?

**Comment by folieadrien** [comment]
Replace in fig.yml:

```
web:
  build: .
  command: rake run
  ports:
    - '80:3000'
```

**Comment by bparanj** [comment]
When I use nohup:
root@localhost:~/grounds.io# RAILS_ENV=production nohup make run &
root@localhost:~/grounds.io# nohup: ignoring input and appending output to ‘nohup.out’

It ignores input and the site goes down. Is there another way to deploy and run it using Capistrano or Fabric?

**Comment by folieadrien** [comment]
I think `fig` is not playing nice with `nohup`, but fig can run everything in the background, il will add a `make` task to do that.

**Comment by folieadrien** [comment]
In the meantime you can try:
`RAILS_ENV=production SECRET_KEY_BASE="your secret key" fig up -d`

**Comment by bparanj** [comment]
The workaround works fine. Just tested on iPad, it does not work on Chrome or Safari.

**Comment by folieadrien** [comment]
Is you iPad connected over 3G/4G ?

**Comment by bparanj** [comment]
It's connected to my home WiFi network.

**Comment by folieadrien** [comment]
is it working with beta.42grounds.io ?

**Comment by bparanj** [comment]
No, it does not. I tested on Chrome and Safari on my iPad running iOS 5.1 (9B176).

**Comment by folieadrien** [comment]
I found something: http://stackoverflow.com/questions/16796106/socket-io-ipad-always-gets-a-timeout-although-it-is-connected.

In fact I have tested it with an iPad running iOS 7 and 8 and it's working well.
I am sorry, I can't do more for this one, I don't have any iPad running iOS 5.1.

**Comment by bparanj** [comment]
No problem. It's great if it works on the later versions of iOS. It works on my iPhone running iOS 7.1.1
