### ISSUE TITLE
What is the connection between grounds.io and grounds-exec do I need both?

### ISSUE THREAD

**Issue by CrashyBang** [grounds/grounds.io#135]
Hey just reading through the documentation trying to set up locally etc... what is the connection between [grounds.io](https://github.com/grounds/grounds.io) repository and the [grounds-exec](https://github.com/grounds/grounds-exec) reposiotry, and how do I make them work together?

And as a side note, what role to grounds-images play, is the actual code runner in there? All very exciting :)

**Comment by foliea** [comment]
Grounds is splitted in three main parts:

**grounds.io**: The web application.
**grounds-exec**: The code runner.
**grounds-images**: A docker image builder, to build every language stack images required by Grounds (e.g. C#, Ruby, Golang, ect...).

**grounds.io** already includes **grounds-exec** through its docker image, **docker-compose** will run a instance of **grounds-exec** in the background and resolves its url according to the environment variable: **DOCKER_URL**.

You can check this file https://github.com/grounds/grounds.io/blob/master/docker-compose.yml which describe the whole stack.

If you have docker installed and the Docker API exposed to the outside world it should be pretty straightforward, you only need to follow the documentation of **grounds.io**: https://github.com/grounds/grounds.io/blob/master/README.md

If you are new to docker, do not hesitate I will gladly do my best to help you :)

**Comment by CrashyBang** [comment]
Thank you, will keep trying and let you know if I hit any issues (very new to docker) thank you so much!
