### ISSUE TITLE
Running in a VM and getting "Connection with remote server failed. Trying to reconnect..." error

### ISSUE THREAD

**Issue by CrashyBang** [grounds/grounds.io#136]
Running through a VM think I have set everything up right but getting "Connection with remote server failed. Trying to reconnect..." errors, any ideas?

**Comment by foliea** [comment]
Can you paste the result of  the following commands:

`docker version`
`docker info`
`echo $DOCKER_URL`, `echo $DOCKER_HOST`,  `echo $DOCKER_CERT_PATH`,  `echo $DOCKER_TLS_VERIFY`

And possibly the whole output of the command that leads you to this error.

Thanks :)
