### ISSUE TITLE
Almost there, but fails in the last minute

### ISSUE THREAD

**Issue by ghost** [grounds/grounds.io#137]
Hi!

I followed the instructions in the README, got to `make run` part and then waited for a while (10 to 15 mins). 

I am not sure about DOCKER_CERT_PATH, should I set this variable to something?

Running Docker version 1.12.0-rc4, build e4a0dbc, experimental. (On macOS)

```
WARNING: The DOCKER_CERT_PATH variable is not set. Defaulting to a blank string.
docker-compose -p groundsio rm --force
WARNING: The DOCKER_CERT_PATH variable is not set. Defaulting to a blank string.
No stopped containers
rm -f tmp/pids/server.pid
RAILS_ENV='development' REPOSITORY='grounds' docker-compose -p groundsio up -d runner
WARNING: The DOCKER_CERT_PATH variable is not set. Defaulting to a blank string.
Creating groundsio_runner_1

ERROR: for runner  create .: "." includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed
ERROR: Encountered errors while bringing up the project.
make: *** [runner] Error 1
```

**Comment by nvulane** [comment]
Hi, 

I have the same issue here. Did you find the solution?

**Comment by ghost** [comment]
Hi, not really. Sorry! 😔

**Comment by nvulane** [comment]
Found the solution, not sure it's a good idea but it's working.

I removed  - '$DOCKER_CERT_PATH:/home/.docker' line from docker-compose.yml file.

**Comment by ghost** [comment]
@nvulane Thanks for persevering and sharing :)

**Comment by ghost** [comment]
Closing as possibly solved.
